### ISSUE TITLE
Many errors occurred when executing the example 2D_collision_avoidance_optimize_final_position.ipynb in default brach "dev"

### ISSUE THREAD

**Issue by iseequeue** [JuJankowski/vp-sto#1]
----> traj_opt = VPSTO(ndof=2)
                  --> TypeError: __init__() got an unexpected keyword argument 'ndof'
----> sol = traj_opt.minimize(loss, q_0=q0) -->TypeError: minimize() got an unexpected keyword argument 'q_0'

File /usr/local/lib/python3.8/dist-packages/vpsto/vpsto.py:111, in VPSTO.minimize(self, loss, q0, dq0, qT, dqT, T)
    109 if dqT is None and T is None:
    110     print('Either T or dqT must be given. Setting dqT to zero.')
--> 111     dqT = np.zeros(self.ndof)
    112 if qT is None and dqT is None:
    113     # qT and dqT are contained in p
    114     dim_x = self.opt.ndof * (self.opt.N_via+1)
AttributeError: 'VPSTO' object has no attribute 'ndof'

/vpsto/vp-sto/examples/2D_collision_avoidance_optimize_final_position.ipynb Cell 6 line 4
           sol = traj_opt.minimize(loss, q0=q0)
           t_traj = np.linspace(0, sol.T_best, 1000)
---->  pos, vel, acc = sol.get_trajectory(t_traj)
          print('Movement duration: ', sol.T_best)
AttributeError: 'VPSTOSolution' object has no attribute 'get_trajectory'

Solution: switch to branch "jax-dev" and install two more dependencies:
1. pip install -U "jax[cpu]"
2. pip install evosax

**Comment by brudermueller** [comment]
Hi @iseequeue, 
indeed the branch `jax-dev` is currently the more recent/maintained one. It is on our to-do list to update the repository and clean up the branches. Let me know if there are any further questions in the meantime!
