### ISSUE TITLE
Could you provide the detail mathematics about OBF?

### ISSUE THREAD

**Issue by CodingCatMountain** [JuJankowski/vp-sto#2]
Hi, @JuJankowski. How have you been? vp-sto is very interesting! However, I am confused with the OBF. I can understand the basis functions used in Learning from Demonstrations, e.g., Gaussian Basis Function. However, I cannot get inside of the mathematics of OBF. It is too abstract. I wander whether can you provide a detail mathematics about OBF or not. Looking forward to your reply! : ) 

Yours sincerely, Woody.

**Comment by CodingCatMountain** [comment]
@brudermueller Hi, mueller. Could you help me to understand this problem? :)

**Comment by brudermueller** [comment]
Hello @CodingCatMountain, 
sorry for the late reply, I have only seen the issue now! The mathematics and theory of OBF is formulated in this [paper](https://ieeexplore.ieee.org/abstract/document/9695495?casa_token=c9L5ga5u2kUAAAAA:qihdGm9HacxPLaCj4-qm-WMS6nj3dl4iTLFDgAibvWrXbxBbLVmx15Y9dUUBXvPc9F4-aGFaGg) (cf. Sec III a). 
Let me know if you have further questions!
