### ISSUE TITLE
Some dumb questions

### ISSUE THREAD

**Issue by Royboy1998** [JuJankowski/vp-sto#3]
Hey guys, I've run the example 2d code and it is very interesting. I am wondering whether it can be adapted to 3D or any chance you will update the examples that work in 3D.

**Comment by JuJankowski** [comment]
Hi, the `ndof` argument specifies how many dimensions your position has. If you set it to 3, you get 3D trajectories. The visualization of things becomes a bit more involved with 3D, that's why examples are in 2D.

**Comment by Royboy1998** [comment]
> Hi, the `ndof` argument specifies how many dimensions your position has. If you set it to 3, you get 3D trajectories. The visualization of things becomes a bit more involved with 3D, that's why examples are in 2D.

Thank you for your time and reply! Yes I did set ndof to 3 in the first place but I forgot to modify other variables in a 3d manner. Now the optimization works. Yet I had a hard time finding a way to represent 3D obstacles so that I had to exclude the collision loss. Do you know any lib or tool that can do 3D representation？ Thank you in advance.

**Comment by JuJankowski** [comment]
Great! A standard library for collision checking is fcl: https://github.com/flexible-collision-library/fcl. There are Python wrappers that would help you integrate it with your Python code.

**Comment by Royboy1998** [comment]
> Great! A standard library for collision checking is fcl: https://github.com/flexible-collision-library/fcl. There are Python wrappers that would help you integrate it with your Python code.

Thanks a lot!  I will try it out. That's a lot for me.

**Comment by Royboy1998** [comment]
@JuJankowski Hi Jankowski, I've lately looked into the demo code 2d predictive sampling and found that : sample_trajectories() method returns a group of candidate trajectories and the cost function selects the best one rather than applying any optimization(including the CMA-ES) algorithm to converge on one,which seems not covered in your paper . 
I am wondering if there's any doc or paper that can explains this sampling method so that I can understand this in a better way.
Thank you!

**Comment by JuJankowski** [comment]
Hi, indeed the notebook [2D_predictive_sampling.ipynb](https://github.com/JuJankowski/vp-sto/blob/dev/examples/2D_predictive_sampling.ipynb) is the only one that does not follow closely the algorithm described in the paper. In general, we run _M_ CMA-ES iterations either until convergence or until a pre-defined number of iterations is reached. The best performing sample over all iterations is then returned as solution. You can see the predictive sampling case as an extreme case where this pre-defined number is 1, meaning that we simply evaluate the first population and return the best one. The notebook contains some other mechanisms as well that are also not discussed in publications (not yet at least). For reference, you could take a look at this [Predictive Sampling paper](https://arxiv.org/abs/2212.00541), which introduces the idea of predictive sampling in a model-predictive controller.

**Comment by Royboy1998** [comment]
> Hi, indeed the notebook [2D_predictive_sampling.ipynb](https://github.com/JuJankowski/vp-sto/blob/dev/examples/2D_predictive_sampling.ipynb) is the only one that does not follow closely the algorithm described in the paper. In general, we run _M_ CMA-ES iterations either until convergence or until a pre-defined number of iterations is reached. The best performing sample over all iterations is then returned as solution. You can see the predictive sampling case as an extreme case where this pre-defined number is 1, meaning that we simply evaluate the first population and return the best one. The notebook contains some other mechanisms as well that are also not discussed in publications (not yet at least). For reference, you could take a look at this [Predictive Sampling paper](https://arxiv.org/abs/2212.00541), which introduces the idea of predictive sampling in a model-predictive controller.

Thank you for your answer and kindly share of the paper.It now cleared up my confusion :-D
